---
#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: '3.8'

services:

    # web app
    boca-web:
        image: boca-web-auth
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            # database configuration
            # privileged user password
            - BOCA_DB_SUPER_PASSWORD=superpass
            #######################
            # authorization setup
            #######################
            # specifies the authentication method to use. The possible choices
            # are summarized below (if unspecified then password authentication
            # is used):
            #  - password: require the user to supply a password
            #  - ldap: authenticate using a LDAP server
            #  - google: authenticate using a Google account
            - BOCA_AUTH_METHOD=password
            # specifies custom BOCA users. If unspecified then considers the
            # default system and admin, which use the default authentication
            # method (password).
            - BOCA_SYSTEM_USER=system
            - BOCA_ADMIN_USER=admin
            - BOCA_LOCAL_TEAM_USER=teamuser
        ports: 
            - 8001:80
        volumes:
            - ./src/index.php:/var/www/boca/src/index.php
            - ./src/flog.php:/var/www/boca/src/flog.php
            - ./src/fcontest.php:/var/www/boca/src/fcontest.php
            - ./src/admin/user.php:/var/www/boca/src/admin/user.php
            - ./src/optionlower.php:/var/www/boca/src/optionlower.php
            - ./src/ldap.php:/var/www/boca/src/ldap.php
            - ./src/googleclient.php:/var/www/boca/src/googleclient.php

    # # online judge
    # boca-jail:
    #     image: ghcr.io/joaofazolo/boca-docker/boca-jail:1.2
    #     privileged: true

    # database
    boca-db:
        image: postgres:14-alpine
        environment:
            # database configuration
            # privileged user password
            - POSTGRES_PASSWORD=superpass
